packages:
  - apps/*
  - services/*
  - packages/*

ignoredBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - '@swc/core'
  - '@tailwindcss/oxide'
  - bcrypt
  - esbuild
  - nx
  - prisma

onlyBuiltDependencies:
  - better-sqlite3
  - puppeteer
  - sharp
