"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Disabled = exports.TripFAQ = exports.Multiple = exports.Default = void 0;
var jsx_runtime_1 = require("react/jsx-runtime");
var accordion_1 = require("./accordion");
var meta = {
    title: 'Components/UI/Accordion',
    component: accordion_1.Accordion,
    parameters: {
        layout: 'centered',
    },
};
exports.default = meta;
exports.Default = {
    render: function () { return ((0, jsx_runtime_1.jsx)("div", { className: 'w-full max-w-md mx-auto', children: (0, jsx_runtime_1.jsxs)(accordion_1.Accordion, { type: 'single', collapsible: true, children: [(0, jsx_runtime_1.jsxs)(accordion_1.AccordionItem, { value: 'item-1', children: [(0, jsx_runtime_1.jsx)(accordion_1.AccordionTrigger, { children: "Is it accessible?" }), (0, jsx_runtime_1.jsx)(accordion_1.AccordionContent, { children: "Yes. It adheres to the WAI-ARIA design pattern." })] }), (0, jsx_runtime_1.jsxs)(accordion_1.AccordionItem, { value: 'item-2', children: [(0, jsx_runtime_1.jsx)(accordion_1.AccordionTrigger, { children: "Is it styled?" }), (0, jsx_runtime_1.jsx)(accordion_1.AccordionContent, { children: "Yes. It comes with default styles that matches the other components' aesthetic." })] }), (0, jsx_runtime_1.jsxs)(accordion_1.AccordionItem, { value: 'item-3', children: [(0, jsx_runtime_1.jsx)(accordion_1.AccordionTrigger, { children: "Is it animated?" }), (0, jsx_runtime_1.jsx)(accordion_1.AccordionContent, { children: "Yes. It's animated by default, but you can disable it if you prefer." })] })] }) })); },
};
exports.Multiple = {
    render: function () { return ((0, jsx_runtime_1.jsx)("div", { className: 'w-full max-w-md mx-auto', children: (0, jsx_runtime_1.jsxs)(accordion_1.Accordion, { type: 'multiple', defaultValue: ['item-1', 'item-3'], children: [(0, jsx_runtime_1.jsxs)(accordion_1.AccordionItem, { value: 'item-1', children: [(0, jsx_runtime_1.jsx)(accordion_1.AccordionTrigger, { children: "Trip Planning" }), (0, jsx_runtime_1.jsx)(accordion_1.AccordionContent, { children: "Plan your perfect trip with our comprehensive tools including itinerary builder, budget tracker, and destination guides." })] }), (0, jsx_runtime_1.jsxs)(accordion_1.AccordionItem, { value: 'item-2', children: [(0, jsx_runtime_1.jsx)(accordion_1.AccordionTrigger, { children: "Accommodation" }), (0, jsx_runtime_1.jsx)(accordion_1.AccordionContent, { children: "Find and book the perfect place to stay. Compare hotels, hostels, vacation rentals, and more." })] }), (0, jsx_runtime_1.jsxs)(accordion_1.AccordionItem, { value: 'item-3', children: [(0, jsx_runtime_1.jsx)(accordion_1.AccordionTrigger, { children: "Activities" }), (0, jsx_runtime_1.jsx)(accordion_1.AccordionContent, { children: "Discover exciting activities and experiences at your destination. Book tours, tickets, and unique local experiences." })] })] }) })); },
};
exports.TripFAQ = {
    render: function () { return ((0, jsx_runtime_1.jsxs)("div", { className: 'w-full max-w-2xl mx-auto', children: [(0, jsx_runtime_1.jsx)("h2", { className: 'text-2xl font-bold mb-4', children: "Frequently Asked Questions" }), (0, jsx_runtime_1.jsxs)(accordion_1.Accordion, { type: 'single', collapsible: true, className: 'w-full', children: [(0, jsx_runtime_1.jsxs)(accordion_1.AccordionItem, { value: 'item-1', children: [(0, jsx_runtime_1.jsx)(accordion_1.AccordionTrigger, { children: "How do I create a new trip?" }), (0, jsx_runtime_1.jsx)(accordion_1.AccordionContent, { children: "Click the \"New Trip\" button in the dashboard. You'll be guided through a step-by-step wizard where you can enter your destination, dates, trip type, and other details." })] }), (0, jsx_runtime_1.jsxs)(accordion_1.AccordionItem, { value: 'item-2', children: [(0, jsx_runtime_1.jsx)(accordion_1.AccordionTrigger, { children: "Can I share my trip with others?" }), (0, jsx_runtime_1.jsx)(accordion_1.AccordionContent, { children: "Yes! You can invite collaborators to your trip by clicking the \"Share\" button in the trip settings. They'll be able to view and edit the trip details with you in real-time." })] }), (0, jsx_runtime_1.jsxs)(accordion_1.AccordionItem, { value: 'item-3', children: [(0, jsx_runtime_1.jsx)(accordion_1.AccordionTrigger, { children: "How do I track my budget?" }), (0, jsx_runtime_1.jsx)(accordion_1.AccordionContent, { children: "Navigate to the Budget section of your trip. You can add expenses, set budget limits for different categories, and track your spending throughout your journey." })] }), (0, jsx_runtime_1.jsxs)(accordion_1.AccordionItem, { value: 'item-4', children: [(0, jsx_runtime_1.jsx)(accordion_1.AccordionTrigger, { children: "Is my data backed up?" }), (0, jsx_runtime_1.jsx)(accordion_1.AccordionContent, { children: "All your trip data is automatically backed up to the cloud. You can access your trips from any device by logging into your account." })] })] })] })); },
};
exports.Disabled = {
    render: function () { return ((0, jsx_runtime_1.jsx)("div", { className: 'w-full max-w-md mx-auto', children: (0, jsx_runtime_1.jsxs)(accordion_1.Accordion, { type: 'single', collapsible: true, children: [(0, jsx_runtime_1.jsxs)(accordion_1.AccordionItem, { value: 'item-1', children: [(0, jsx_runtime_1.jsx)(accordion_1.AccordionTrigger, { children: "Available Feature" }), (0, jsx_runtime_1.jsx)(accordion_1.AccordionContent, { children: "This feature is available for all users." })] }), (0, jsx_runtime_1.jsxs)(accordion_1.AccordionItem, { value: 'item-2', disabled: true, children: [(0, jsx_runtime_1.jsx)(accordion_1.AccordionTrigger, { disabled: true, children: "Premium Feature (Disabled)" }), (0, jsx_runtime_1.jsx)(accordion_1.AccordionContent, { children: "This content is not accessible because the item is disabled." })] }), (0, jsx_runtime_1.jsxs)(accordion_1.AccordionItem, { value: 'item-3', children: [(0, jsx_runtime_1.jsx)(accordion_1.AccordionTrigger, { children: "Another Available Feature" }), (0, jsx_runtime_1.jsx)(accordion_1.AccordionContent, { children: "This feature is also available for all users." })] })] }) })); },
};
