"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Interactive = exports.LongContent = exports.WithoutTitle = exports.TripOrganizationExamples = exports.WithIcons = exports.AllVariants = exports.Default = void 0;
var jsx_runtime_1 = require("react/jsx-runtime");
var alert_1 = require("./alert");
var StoryWrapper_1 = require("../StoryWrapper");
var lucide_react_1 = require("lucide-react");
require("../../styles/story-fonts.css");
var meta = {
    title: 'Components/UI/Alert',
    component: alert_1.Alert,
    parameters: {
        layout: 'centered',
    },
};
exports.default = meta;
exports.Default = {
    render: function () { return ((0, jsx_runtime_1.jsx)(alert_1.Alert, { children: (0, jsx_runtime_1.jsx)(alert_1.AlertDescription, { children: "This is a default alert." }) })); },
};
exports.AllVariants = {
    render: function () { return ((0, jsx_runtime_1.jsx)(StoryWrapper_1.ComponentStory, { title: 'Alert Variants', description: 'All available alert variants with icons and descriptions', background: 'gradient-blue', children: (0, jsx_runtime_1.jsxs)("div", { className: 'space-y-6', children: [(0, jsx_runtime_1.jsxs)("div", { className: 'space-y-4', children: [(0, jsx_runtime_1.jsxs)(alert_1.Alert, { children: [(0, jsx_runtime_1.jsx)(lucide_react_1.Info, { className: 'h-4 w-4' }), (0, jsx_runtime_1.jsx)(alert_1.AlertTitle, { children: "Information" }), (0, jsx_runtime_1.jsx)(alert_1.AlertDescription, { children: "Your trip to Paris has been successfully saved to your itinerary." })] }), (0, jsx_runtime_1.jsxs)(alert_1.Alert, { variant: 'destructive', children: [(0, jsx_runtime_1.jsx)(lucide_react_1.XCircle, { className: 'h-4 w-4' }), (0, jsx_runtime_1.jsx)(alert_1.AlertTitle, { children: "Error" }), (0, jsx_runtime_1.jsx)(alert_1.AlertDescription, { children: "Unable to book accommodation. Please check your payment details and try again." })] })] }), (0, jsx_runtime_1.jsxs)("div", { className: 'p-4 bg-blue-50 rounded-lg border border-blue-100', children: [(0, jsx_runtime_1.jsx)("h4", { className: 'font-semibold text-blue-900 mb-2', children: "Variant Guidelines:" }), (0, jsx_runtime_1.jsxs)("ul", { className: 'text-sm text-blue-800 space-y-1', children: [(0, jsx_runtime_1.jsxs)("li", { children: ["\u2022 ", (0, jsx_runtime_1.jsx)("strong", { children: "Default:" }), " General information, confirmations, neutral messages"] }), (0, jsx_runtime_1.jsxs)("li", { children: ["\u2022 ", (0, jsx_runtime_1.jsx)("strong", { children: "Destructive:" }), " Errors, warnings, critical issues requiring attention"] })] })] })] }) })); },
};
exports.WithIcons = {
    render: function () { return ((0, jsx_runtime_1.jsx)(StoryWrapper_1.ComponentStory, { title: 'Alert with Icons', description: 'Alerts enhanced with contextual icons for better visual communication', background: 'gradient-green', children: (0, jsx_runtime_1.jsxs)("div", { className: 'space-y-4', children: [(0, jsx_runtime_1.jsxs)(alert_1.Alert, { children: [(0, jsx_runtime_1.jsx)(lucide_react_1.CheckCircle, { className: 'h-4 w-4' }), (0, jsx_runtime_1.jsx)(alert_1.AlertTitle, { children: "Trip Confirmed" }), (0, jsx_runtime_1.jsx)(alert_1.AlertDescription, { children: "Your 7-day European adventure has been confirmed. Check your email for booking details." })] }), (0, jsx_runtime_1.jsxs)(alert_1.Alert, { children: [(0, jsx_runtime_1.jsx)(lucide_react_1.MapPin, { className: 'h-4 w-4' }), (0, jsx_runtime_1.jsx)(alert_1.AlertTitle, { children: "New Destination Added" }), (0, jsx_runtime_1.jsx)(alert_1.AlertDescription, { children: "Barcelona has been added to your itinerary. Don't forget to check visa requirements." })] }), (0, jsx_runtime_1.jsxs)(alert_1.Alert, { children: [(0, jsx_runtime_1.jsx)(lucide_react_1.Calendar, { className: 'h-4 w-4' }), (0, jsx_runtime_1.jsx)(alert_1.AlertTitle, { children: "Schedule Update" }), (0, jsx_runtime_1.jsx)(alert_1.AlertDescription, { children: "Your flight departure time has been moved to 2:30 PM. Please arrive at the airport 2 hours early." })] }), (0, jsx_runtime_1.jsxs)(alert_1.Alert, { variant: 'destructive', children: [(0, jsx_runtime_1.jsx)(lucide_react_1.AlertTriangle, { className: 'h-4 w-4' }), (0, jsx_runtime_1.jsx)(alert_1.AlertTitle, { children: "Budget Alert" }), (0, jsx_runtime_1.jsx)(alert_1.AlertDescription, { children: "You've exceeded your daily budget by $45. Consider adjusting your spending for upcoming days." })] })] }) })); },
};
exports.TripOrganizationExamples = {
    render: function () { return ((0, jsx_runtime_1.jsx)(StoryWrapper_1.ComponentStory, { title: 'Trip Organization Alerts', description: 'Real-world examples of alerts in a trip planning context', background: 'gradient-orange', children: (0, jsx_runtime_1.jsxs)("div", { className: 'space-y-4', children: [(0, jsx_runtime_1.jsxs)(alert_1.Alert, { children: [(0, jsx_runtime_1.jsx)(lucide_react_1.CheckCircle, { className: 'h-4 w-4' }), (0, jsx_runtime_1.jsx)(alert_1.AlertTitle, { children: "Accommodation Booked" }), (0, jsx_runtime_1.jsx)(alert_1.AlertDescription, { children: "Hotel Cosmos in Prague has been booked for 3 nights (June 15-18). Confirmation number: #HTC789456" })] }), (0, jsx_runtime_1.jsxs)(alert_1.Alert, { children: [(0, jsx_runtime_1.jsx)(lucide_react_1.Info, { className: 'h-4 w-4' }), (0, jsx_runtime_1.jsx)(alert_1.AlertTitle, { children: "Weather Update" }), (0, jsx_runtime_1.jsx)(alert_1.AlertDescription, { children: "Expect rain in Amsterdam this weekend. Pack an umbrella and consider indoor activities like visiting the Van Gogh Museum." })] }), (0, jsx_runtime_1.jsxs)(alert_1.Alert, { variant: 'destructive', children: [(0, jsx_runtime_1.jsx)(lucide_react_1.XCircle, { className: 'h-4 w-4' }), (0, jsx_runtime_1.jsx)(alert_1.AlertTitle, { children: "Flight Cancelled" }), (0, jsx_runtime_1.jsx)(alert_1.AlertDescription, { children: "Your flight BA456 on March 20th has been cancelled. We've automatically rebooked you on the next available flight departing 4 hours later." })] }), (0, jsx_runtime_1.jsxs)(alert_1.Alert, { children: [(0, jsx_runtime_1.jsx)(lucide_react_1.DollarSign, { className: 'h-4 w-4' }), (0, jsx_runtime_1.jsx)(alert_1.AlertTitle, { children: "Budget Tracking" }), (0, jsx_runtime_1.jsx)(alert_1.AlertDescription, { children: "You've spent $280 of your $500 daily budget. You have $220 remaining for dinner and evening activities." })] })] }) })); },
};
exports.WithoutTitle = {
    render: function () { return ((0, jsx_runtime_1.jsx)(StoryWrapper_1.ComponentStory, { title: 'Alerts Without Titles', description: 'Simple alerts with just descriptions for quick notifications', background: 'gradient-purple', children: (0, jsx_runtime_1.jsxs)("div", { className: 'space-y-4', children: [(0, jsx_runtime_1.jsxs)(alert_1.Alert, { children: [(0, jsx_runtime_1.jsx)(lucide_react_1.CheckCircle, { className: 'h-4 w-4' }), (0, jsx_runtime_1.jsx)(alert_1.AlertDescription, { children: "Your itinerary has been automatically saved." })] }), (0, jsx_runtime_1.jsxs)(alert_1.Alert, { children: [(0, jsx_runtime_1.jsx)(lucide_react_1.Info, { className: 'h-4 w-4' }), (0, jsx_runtime_1.jsx)(alert_1.AlertDescription, { children: "Remember to check-in online 24 hours before your flight." })] }), (0, jsx_runtime_1.jsxs)(alert_1.Alert, { variant: 'destructive', children: [(0, jsx_runtime_1.jsx)(lucide_react_1.AlertTriangle, { className: 'h-4 w-4' }), (0, jsx_runtime_1.jsx)(alert_1.AlertDescription, { children: "Internet connection lost. Working in offline mode." })] })] }) })); },
};
exports.LongContent = {
    render: function () { return ((0, jsx_runtime_1.jsx)(StoryWrapper_1.ComponentStory, { title: 'Alerts with Long Content', description: 'How alerts handle longer text content and multiple paragraphs', background: 'gradient-pink', children: (0, jsx_runtime_1.jsxs)("div", { className: 'space-y-4', children: [(0, jsx_runtime_1.jsxs)(alert_1.Alert, { children: [(0, jsx_runtime_1.jsx)(lucide_react_1.Info, { className: 'h-4 w-4' }), (0, jsx_runtime_1.jsx)(alert_1.AlertTitle, { children: "Travel Insurance Recommendation" }), (0, jsx_runtime_1.jsxs)(alert_1.AlertDescription, { children: [(0, jsx_runtime_1.jsx)("p", { children: "We highly recommend purchasing travel insurance for your upcoming European trip. Travel insurance can protect you from unexpected costs related to:" }), (0, jsx_runtime_1.jsxs)("ul", { className: 'mt-2 ml-4 list-disc space-y-1', children: [(0, jsx_runtime_1.jsx)("li", { children: "Trip cancellations or interruptions" }), (0, jsx_runtime_1.jsx)("li", { children: "Medical emergencies abroad" }), (0, jsx_runtime_1.jsx)("li", { children: "Lost or stolen luggage" }), (0, jsx_runtime_1.jsx)("li", { children: "Flight delays and missed connections" })] }), (0, jsx_runtime_1.jsx)("p", { className: 'mt-2', children: "Visit our insurance partners page to compare options and get quotes." })] })] }), (0, jsx_runtime_1.jsxs)(alert_1.Alert, { variant: 'destructive', children: [(0, jsx_runtime_1.jsx)(lucide_react_1.AlertTriangle, { className: 'h-4 w-4' }), (0, jsx_runtime_1.jsx)(alert_1.AlertTitle, { children: "Important Visa Information" }), (0, jsx_runtime_1.jsx)(alert_1.AlertDescription, { children: "Your passport expires in 4 months. Many countries require passports to be valid for at least 6 months beyond your travel dates. Please check the specific requirements for your destinations: France, Italy, and Spain. Consider renewing your passport before your trip to avoid any travel complications or entry denials at border control." })] })] }) })); },
};
exports.Interactive = {
    render: function () { return ((0, jsx_runtime_1.jsx)(StoryWrapper_1.ComponentStory, { title: 'Interactive Alert Demo', description: 'Clickable alerts demonstrating user interactions', background: 'gradient-green', children: (0, jsx_runtime_1.jsxs)("div", { className: 'space-y-4', children: [(0, jsx_runtime_1.jsxs)(alert_1.Alert, { className: 'cursor-pointer hover:bg-accent/50 transition-colors', onClick: function () { return alert('Alert clicked! This could navigate to trip details.'); }, children: [(0, jsx_runtime_1.jsx)(lucide_react_1.MapPin, { className: 'h-4 w-4' }), (0, jsx_runtime_1.jsx)(alert_1.AlertTitle, { children: "New Destination Suggestion" }), (0, jsx_runtime_1.jsx)(alert_1.AlertDescription, { children: "Based on your interests, we recommend adding Porto to your Portugal itinerary. Click to explore." })] }), (0, jsx_runtime_1.jsxs)(alert_1.Alert, { variant: 'destructive', className: 'cursor-pointer hover:bg-destructive/5 transition-colors', onClick: function () { return alert('Critical alert clicked! This could open a help dialog.'); }, children: [(0, jsx_runtime_1.jsx)(lucide_react_1.AlertTriangle, { className: 'h-4 w-4' }), (0, jsx_runtime_1.jsx)(alert_1.AlertTitle, { children: "Action Required" }), (0, jsx_runtime_1.jsx)(alert_1.AlertDescription, { children: "Your credit card on file expires next month. Update your payment method to avoid booking issues." })] })] }) })); },
};
