"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Interactive = exports.FormValidation = exports.AutoResize = exports.CharacterCounter = exports.ReviewAndFeedback = exports.TripPlanningTextareas = exports.BasicStates = exports.Default = void 0;
var jsx_runtime_1 = require("react/jsx-runtime");
var textarea_1 = require("./textarea");
var label_1 = require("./label");
var StoryWrapper_1 = require("../StoryWrapper");
var react_1 = require("react");
require("../../styles/story-fonts.css");
var meta = {
    title: 'Components/UI/Textarea',
    component: textarea_1.Textarea,
    parameters: {
        layout: 'centered',
    },
};
exports.default = meta;
exports.Default = {
    render: function () { return (0, jsx_runtime_1.jsx)(textarea_1.Textarea, { placeholder: 'Enter your message...' }); },
};
exports.BasicStates = {
    render: function () { return ((0, jsx_runtime_1.jsx)(StoryWrapper_1.ComponentStory, { title: 'Textarea States', description: 'Different textarea states including normal, disabled, readonly, and error states', background: 'gradient-blue', children: (0, jsx_runtime_1.jsx)("div", { className: 'space-y-6 max-w-md', children: (0, jsx_runtime_1.jsxs)("div", { className: 'space-y-4', children: [(0, jsx_runtime_1.jsxs)("div", { children: [(0, jsx_runtime_1.jsx)(label_1.Label, { htmlFor: 'normal-textarea', className: 'block mb-2', children: "Normal State" }), (0, jsx_runtime_1.jsx)(textarea_1.Textarea, { id: 'normal-textarea', placeholder: 'Describe your travel experience...', rows: 3 })] }), (0, jsx_runtime_1.jsxs)("div", { children: [(0, jsx_runtime_1.jsx)(label_1.Label, { htmlFor: 'disabled-textarea', className: 'block mb-2 opacity-50', children: "Disabled State" }), (0, jsx_runtime_1.jsx)(textarea_1.Textarea, { id: 'disabled-textarea', placeholder: 'This textarea is disabled', disabled: true, rows: 3 })] }), (0, jsx_runtime_1.jsxs)("div", { children: [(0, jsx_runtime_1.jsx)(label_1.Label, { htmlFor: 'readonly-textarea', className: 'block mb-2', children: "Readonly State" }), (0, jsx_runtime_1.jsx)(textarea_1.Textarea, { id: 'readonly-textarea', value: 'This content cannot be edited. It contains important travel information that should remain unchanged.', readOnly: true, rows: 3 })] }), (0, jsx_runtime_1.jsxs)("div", { children: [(0, jsx_runtime_1.jsx)(label_1.Label, { htmlFor: 'error-textarea', className: 'block mb-2 text-red-700', children: "Error State" }), (0, jsx_runtime_1.jsx)(textarea_1.Textarea, { id: 'error-textarea', placeholder: 'This field has an error', className: 'border-red-300 focus-visible:border-red-500 focus-visible:ring-red-200', "aria-invalid": 'true', rows: 3 }), (0, jsx_runtime_1.jsx)("p", { className: 'text-xs text-red-600 mt-1', children: "Please provide a valid description" })] }), (0, jsx_runtime_1.jsxs)("div", { children: [(0, jsx_runtime_1.jsx)(label_1.Label, { htmlFor: 'success-textarea', className: 'block mb-2 text-green-700', children: "Success State" }), (0, jsx_runtime_1.jsx)(textarea_1.Textarea, { id: 'success-textarea', value: 'Your trip review has been successfully submitted!', className: 'border-green-300 focus-visible:border-green-500 focus-visible:ring-green-200', readOnly: true, rows: 2 }), (0, jsx_runtime_1.jsx)("p", { className: 'text-xs text-green-600 mt-1', children: "Review saved successfully" })] })] }) }) })); },
};
exports.TripPlanningTextareas = {
    render: function () { return ((0, jsx_runtime_1.jsx)(StoryWrapper_1.ComponentStory, { title: 'Trip Planning Textareas', description: 'Real-world examples of textareas used in trip organization', background: 'gradient-green', children: (0, jsx_runtime_1.jsx)("div", { className: 'space-y-6', children: (0, jsx_runtime_1.jsxs)("div", { className: 'bg-white p-6 rounded-lg border shadow-sm max-w-2xl', children: [(0, jsx_runtime_1.jsx)("h3", { className: 'text-lg font-semibold text-gray-900 mb-6', children: "Trip Planning Form" }), (0, jsx_runtime_1.jsxs)("div", { className: 'space-y-6', children: [(0, jsx_runtime_1.jsxs)("div", { children: [(0, jsx_runtime_1.jsxs)(label_1.Label, { htmlFor: 'trip-description', className: 'block mb-2 font-medium', children: ["Trip Description", (0, jsx_runtime_1.jsx)("span", { className: 'text-xs font-normal text-gray-500 ml-1', children: "(optional)" })] }), (0, jsx_runtime_1.jsx)(textarea_1.Textarea, { id: 'trip-description', placeholder: "Describe what you want to experience on this trip. Include any specific interests, must-see places, or activities you're excited about...", rows: 4 }), (0, jsx_runtime_1.jsx)("p", { className: 'text-xs text-gray-500 mt-1', children: "This helps us personalize your itinerary recommendations" })] }), (0, jsx_runtime_1.jsxs)("div", { children: [(0, jsx_runtime_1.jsx)(label_1.Label, { htmlFor: 'special-requirements', className: 'block mb-2 font-medium', children: "Special Requirements & Preferences" }), (0, jsx_runtime_1.jsx)(textarea_1.Textarea, { id: 'special-requirements', placeholder: 'Dietary restrictions, accessibility needs, medical considerations, travel pace preferences, accommodation requirements, etc.', rows: 3 })] }), (0, jsx_runtime_1.jsxs)("div", { children: [(0, jsx_runtime_1.jsxs)(label_1.Label, { htmlFor: 'previous-experience', className: 'block mb-2 font-medium', children: ["Previous Travel Experience", (0, jsx_runtime_1.jsx)("span", { className: 'text-xs font-normal text-gray-500 ml-1', children: "(optional)" })] }), (0, jsx_runtime_1.jsx)(textarea_1.Textarea, { id: 'previous-experience', placeholder: "Tell us about places you've visited before and what you loved or didn't enjoy about those experiences...", rows: 3 })] }), (0, jsx_runtime_1.jsxs)("div", { children: [(0, jsx_runtime_1.jsxs)(label_1.Label, { htmlFor: 'additional-notes', className: 'block mb-2 font-medium', children: ["Additional Notes", (0, jsx_runtime_1.jsx)("span", { className: 'text-xs font-normal text-gray-500 ml-1', children: "(optional)" })] }), (0, jsx_runtime_1.jsx)(textarea_1.Textarea, { id: 'additional-notes', placeholder: "Any other information you'd like us to know...", rows: 2 })] })] })] }) }) })); },
};
exports.ReviewAndFeedback = {
    render: function () { return ((0, jsx_runtime_1.jsx)(StoryWrapper_1.ComponentStory, { title: 'Reviews and Feedback', description: 'Textareas for writing reviews, feedback, and detailed comments', background: 'gradient-purple', children: (0, jsx_runtime_1.jsxs)("div", { className: 'space-y-6 max-w-2xl', children: [(0, jsx_runtime_1.jsxs)("div", { className: 'bg-white p-6 rounded-lg border shadow-sm', children: [(0, jsx_runtime_1.jsx)("h3", { className: 'text-lg font-semibold text-gray-900 mb-4', children: "Hotel Review" }), (0, jsx_runtime_1.jsxs)("div", { className: 'flex items-center gap-2 mb-4', children: [(0, jsx_runtime_1.jsx)("span", { className: 'text-sm text-gray-600', children: "Rating:" }), (0, jsx_runtime_1.jsx)("div", { className: 'flex gap-1', children: [1, 2, 3, 4, 5].map(function (star) { return ((0, jsx_runtime_1.jsx)("span", { className: 'text-yellow-400', children: "\u2605" }, star)); }) })] }), (0, jsx_runtime_1.jsxs)("div", { children: [(0, jsx_runtime_1.jsx)(label_1.Label, { htmlFor: 'hotel-review', className: 'block mb-2 font-medium', children: "Share Your Experience" }), (0, jsx_runtime_1.jsx)(textarea_1.Textarea, { id: 'hotel-review', placeholder: 'Tell other travelers about your stay. What did you love? What could be improved? How was the location, service, amenities, etc.?', rows: 5, defaultValue: "Had an amazing stay at Hotel Cosmos in Prague! The location was perfect - just a 5-minute walk from the Old Town Square. The staff was incredibly helpful and spoke great English. Room was clean and spacious with a beautiful view of the city.\n\nThe breakfast buffet had a great variety of local and international options. Only minor complaint was that the WiFi was a bit slow in the evenings, but overall it didn't impact our stay.\n\nWould definitely recommend this hotel to anyone visiting Prague. Great value for money!" }), (0, jsx_runtime_1.jsx)("p", { className: 'text-xs text-gray-500 mt-1', children: "Your review helps other travelers make informed decisions" })] })] }), (0, jsx_runtime_1.jsxs)("div", { className: 'bg-white p-6 rounded-lg border shadow-sm', children: [(0, jsx_runtime_1.jsx)("h3", { className: 'text-lg font-semibold text-gray-900 mb-4', children: "Trip Feedback" }), (0, jsx_runtime_1.jsxs)("div", { children: [(0, jsx_runtime_1.jsx)(label_1.Label, { htmlFor: 'trip-feedback', className: 'block mb-2 font-medium', children: "How was your overall trip experience?" }), (0, jsx_runtime_1.jsx)(textarea_1.Textarea, { id: 'trip-feedback', placeholder: "We'd love to hear about your trip! What were the highlights? Any suggestions for improvement? How was the planning process?", rows: 4 })] })] })] }) })); },
};
var CharacterCounter = function () {
    var _a = (0, react_1.useState)(''), content = _a[0], setContent = _a[1];
    var maxLength = 500;
    var remaining = maxLength - content.length;
    return ((0, jsx_runtime_1.jsx)(StoryWrapper_1.ComponentStory, { title: 'Textarea with Character Counter', description: 'Interactive textarea with real-time character counting and limits', background: 'gradient-orange', children: (0, jsx_runtime_1.jsxs)("div", { className: 'space-y-6 max-w-md', children: [(0, jsx_runtime_1.jsxs)("div", { children: [(0, jsx_runtime_1.jsxs)(label_1.Label, { htmlFor: 'limited-textarea', className: 'block mb-2 font-medium', children: ["Trip Summary", (0, jsx_runtime_1.jsx)("span", { className: 'text-xs font-normal text-gray-500 ml-1', children: "(max 500 characters)" })] }), (0, jsx_runtime_1.jsx)(textarea_1.Textarea, { id: 'limited-textarea', placeholder: 'Summarize your trip in a few sentences...', rows: 4, maxLength: maxLength, value: content, onChange: function (e) { return setContent(e.target.value); }, className: remaining < 50
                                ? 'border-amber-300 focus-visible:border-amber-500 focus-visible:ring-amber-200'
                                : '' }), (0, jsx_runtime_1.jsxs)("div", { className: 'flex justify-between items-center mt-1', children: [(0, jsx_runtime_1.jsxs)("p", { className: "text-xs ".concat(remaining < 50 ? 'text-amber-600' : remaining < 20 ? 'text-red-600' : 'text-gray-500'), children: [remaining, " characters remaining"] }), (0, jsx_runtime_1.jsxs)("p", { className: 'text-xs text-gray-400', children: [content.length, "/", maxLength] })] })] }), (0, jsx_runtime_1.jsxs)("div", { className: 'p-4 bg-orange-50 rounded-lg border border-orange-100', children: [(0, jsx_runtime_1.jsx)("h4", { className: 'font-semibold text-orange-900 mb-2', children: "Character Counter Features:" }), (0, jsx_runtime_1.jsxs)("ul", { className: 'text-sm text-orange-800 space-y-1', children: [(0, jsx_runtime_1.jsx)("li", { children: "\u2022 Real-time character counting" }), (0, jsx_runtime_1.jsx)("li", { children: "\u2022 Color changes when approaching limit" }), (0, jsx_runtime_1.jsx)("li", { children: "\u2022 Visual feedback for user guidance" }), (0, jsx_runtime_1.jsx)("li", { children: "\u2022 Prevents content overflow" })] })] })] }) }));
};
exports.CharacterCounter = CharacterCounter;
exports.AutoResize = {
    render: function () { return ((0, jsx_runtime_1.jsx)(StoryWrapper_1.ComponentStory, { title: 'Auto-Resizing Textarea', description: 'Textarea that automatically adjusts height based on content', background: 'gradient-pink', children: (0, jsx_runtime_1.jsxs)("div", { className: 'space-y-6 max-w-md', children: [(0, jsx_runtime_1.jsxs)("div", { children: [(0, jsx_runtime_1.jsx)(label_1.Label, { htmlFor: 'auto-resize', className: 'block mb-2 font-medium', children: "Detailed Itinerary Notes" }), (0, jsx_runtime_1.jsx)("div", { className: 'relative', children: (0, jsx_runtime_1.jsx)(textarea_1.Textarea, { id: 'auto-resize', placeholder: 'Start typing your detailed itinerary notes here. This textarea will automatically expand as you add more content...', className: 'resize-none overflow-hidden', style: { fieldSizing: 'content' }, onInput: function (e) {
                                    var target = e.target;
                                    target.style.height = 'auto';
                                    target.style.height = target.scrollHeight + 'px';
                                } }) }), (0, jsx_runtime_1.jsx)("p", { className: 'text-xs text-gray-500 mt-1', children: "Textarea automatically expands as you type" })] }), (0, jsx_runtime_1.jsxs)("div", { className: 'space-y-3', children: [(0, jsx_runtime_1.jsx)("h4", { className: 'text-sm font-semibold text-gray-700', children: "Example Content to Test Auto-Resize:" }), (0, jsx_runtime_1.jsxs)("div", { className: 'text-xs text-gray-600 space-y-2', children: [(0, jsx_runtime_1.jsxs)("p", { children: [(0, jsx_runtime_1.jsx)("strong", { children: "Day 1:" }), " Arrive in Paris, check into hotel, evening stroll along the Seine"] }), (0, jsx_runtime_1.jsxs)("p", { children: [(0, jsx_runtime_1.jsx)("strong", { children: "Day 2:" }), " Visit Louvre Museum in the morning, lunch at local caf\u00E9, afternoon at Eiffel Tower"] }), (0, jsx_runtime_1.jsxs)("p", { children: [(0, jsx_runtime_1.jsx)("strong", { children: "Day 3:" }), " Day trip to Versailles Palace, return for dinner in Montmartre"] }), (0, jsx_runtime_1.jsxs)("p", { children: [(0, jsx_runtime_1.jsx)("strong", { children: "Day 4:" }), " Notre-Dame Cathedral, Latin Quarter exploration, evening river cruise"] }), (0, jsx_runtime_1.jsxs)("p", { children: [(0, jsx_runtime_1.jsx)("strong", { children: "Day 5:" }), " Shopping on Champs-\u00C9lys\u00E9es, visit Arc de Triomphe, farewell dinner"] })] })] })] }) })); },
};
exports.FormValidation = {
    render: function () { return ((0, jsx_runtime_1.jsx)(StoryWrapper_1.ComponentStory, { title: 'Textarea Form Validation', description: 'Textareas with various validation states and error handling', background: 'gradient-red', children: (0, jsx_runtime_1.jsx)("div", { className: 'space-y-6 max-w-md', children: (0, jsx_runtime_1.jsxs)("div", { className: 'space-y-5', children: [(0, jsx_runtime_1.jsxs)("div", { children: [(0, jsx_runtime_1.jsx)(label_1.Label, { htmlFor: 'required-field', className: 'block mb-2 font-medium text-red-700', children: "Emergency Contact Information *" }), (0, jsx_runtime_1.jsx)(textarea_1.Textarea, { id: 'required-field', placeholder: 'Please provide emergency contact details...', className: 'border-red-300 focus-visible:border-red-500 focus-visible:ring-red-200', "aria-invalid": 'true', required: true, rows: 3 }), (0, jsx_runtime_1.jsx)("p", { className: 'text-xs text-red-600 mt-1', children: "This field is required" })] }), (0, jsx_runtime_1.jsxs)("div", { children: [(0, jsx_runtime_1.jsx)(label_1.Label, { htmlFor: 'min-length-field', className: 'block mb-2 font-medium text-amber-700', children: "Travel Experience Description" }), (0, jsx_runtime_1.jsx)(textarea_1.Textarea, { id: 'min-length-field', placeholder: 'Please provide at least 50 characters...', className: 'border-amber-300 focus-visible:border-amber-500 focus-visible:ring-amber-200', rows: 3 }), (0, jsx_runtime_1.jsx)("p", { className: 'text-xs text-amber-600 mt-1', children: "Please provide more details (minimum 50 characters)" })] }), (0, jsx_runtime_1.jsxs)("div", { children: [(0, jsx_runtime_1.jsx)(label_1.Label, { htmlFor: 'validated-field', className: 'block mb-2 font-medium text-green-700', children: "Booking Confirmation" }), (0, jsx_runtime_1.jsx)(textarea_1.Textarea, { id: 'validated-field', value: 'Thank you for your booking! Your reservation has been confirmed for Hotel Paradise, Check-in: March 15th, Check-out: March 20th. Confirmation number: ABC123XYZ.', className: 'border-green-300 focus-visible:border-green-500 focus-visible:ring-green-200', readOnly: true, rows: 3 }), (0, jsx_runtime_1.jsx)("p", { className: 'text-xs text-green-600 mt-1', children: "\u2713 Booking details confirmed" })] })] }) }) })); },
};
var Interactive = function () {
    var _a = (0, react_1.useState)(''), feedback = _a[0], setFeedback = _a[1];
    var _b = (0, react_1.useState)(0), wordCount = _b[0], setWordCount = _b[1];
    var handleChange = function (e) {
        var text = e.target.value;
        setFeedback(text);
        var words = text.trim() ? text.trim().split(/\s+/).length : 0;
        setWordCount(words);
    };
    return ((0, jsx_runtime_1.jsx)(StoryWrapper_1.ComponentStory, { title: 'Interactive Textarea Demo', description: 'Advanced textarea with word counting, validation, and real-time feedback', background: 'gradient-blue', children: (0, jsx_runtime_1.jsxs)("div", { className: 'space-y-6 max-w-2xl', children: [(0, jsx_runtime_1.jsxs)("div", { className: 'bg-white p-6 rounded-lg border shadow-sm', children: [(0, jsx_runtime_1.jsx)("h3", { className: 'text-lg font-semibold text-gray-900 mb-4', children: "Activity Feedback Form" }), (0, jsx_runtime_1.jsxs)("div", { children: [(0, jsx_runtime_1.jsxs)(label_1.Label, { htmlFor: 'interactive-feedback', className: 'block mb-2 font-medium', children: ["Tell us about your experience", (0, jsx_runtime_1.jsx)("span", { className: 'text-xs font-normal text-gray-500 ml-1', children: "(minimum 20 words recommended)" })] }), (0, jsx_runtime_1.jsx)(textarea_1.Textarea, { id: 'interactive-feedback', placeholder: "Share your thoughts about the activity, what you enjoyed, what could be improved, and whether you'd recommend it to others...", rows: 5, value: feedback, onChange: handleChange, className: wordCount > 0 && wordCount < 20
                                        ? 'border-amber-300 focus-visible:border-amber-500 focus-visible:ring-amber-200'
                                        : wordCount >= 20
                                            ? 'border-green-300 focus-visible:border-green-500 focus-visible:ring-green-200'
                                            : '' }), (0, jsx_runtime_1.jsxs)("div", { className: 'flex justify-between items-center mt-2', children: [(0, jsx_runtime_1.jsxs)("div", { className: 'flex items-center gap-4', children: [(0, jsx_runtime_1.jsxs)("p", { className: "text-xs ".concat(wordCount >= 20 ? 'text-green-600' : wordCount > 0 ? 'text-amber-600' : 'text-gray-500'), children: [wordCount, " word", wordCount !== 1 ? 's' : ''] }), (0, jsx_runtime_1.jsxs)("p", { className: 'text-xs text-gray-400', children: [feedback.length, " characters"] })] }), wordCount >= 20 && ((0, jsx_runtime_1.jsx)("p", { className: 'text-xs text-green-600', children: "\u2713 Good length for feedback" })), wordCount > 0 && wordCount < 20 && ((0, jsx_runtime_1.jsx)("p", { className: 'text-xs text-amber-600', children: "Consider adding more detail" }))] })] }), feedback && ((0, jsx_runtime_1.jsxs)("div", { className: 'mt-4 p-3 bg-gray-50 rounded-lg', children: [(0, jsx_runtime_1.jsx)("h4", { className: 'text-sm font-medium text-gray-700 mb-2', children: "Preview:" }), (0, jsx_runtime_1.jsx)("p", { className: 'text-sm text-gray-600', children: feedback })] }))] }), (0, jsx_runtime_1.jsxs)("div", { className: 'p-4 bg-blue-50 rounded-lg border border-blue-100', children: [(0, jsx_runtime_1.jsx)("h4", { className: 'font-semibold text-blue-900 mb-2', children: "Interactive Features:" }), (0, jsx_runtime_1.jsxs)("ul", { className: 'text-sm text-blue-800 space-y-1', children: [(0, jsx_runtime_1.jsx)("li", { children: "\u2022 Real-time word and character counting" }), (0, jsx_runtime_1.jsx)("li", { children: "\u2022 Dynamic validation feedback" }), (0, jsx_runtime_1.jsx)("li", { children: "\u2022 Live preview of content" }), (0, jsx_runtime_1.jsx)("li", { children: "\u2022 Visual indicators for quality thresholds" })] })] })] }) }));
};
exports.Interactive = Interactive;
