import type { NewTrip, NewUser, NewPerson, NewLocation, NewItineraryItem } from './schema.js'

// Default user for development
export const sampleUsers: NewUser[] = [
  {
    id: 'user-demo-1',
    name: 'Demo User',
    email: 'demo@pops.travel',
    avatar:
      'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&h=100&fit=crop&crop=face',
  },
]

// Sample people from itineraryService.ts
export const samplePeople: NewPerson[] = [
  {
    id: 'p1',
    name: 'Maria Santos',
    relationshipType: 'family',
    phone: '+55 11 99999-1234',
    notes: 'Cousin in São Paulo',
  },
  {
    id: 'p2',
    name: 'João Silva',
    relationshipType: 'friend',
    whatsapp: '+55 21 88888-5678',
    notes: 'Friend from Rio, knows great restaurants',
  },
  {
    id: 'p3',
    name: 'Ana Costa',
    relationshipType: 'colleague',
    email: 'ana@company.com',
    notes: 'Work contact for research interviews',
  },
]

// Sample locations from itineraryService.ts
export const sampleLocations: NewLocation[] = [
  {
    id: 'l1',
    name: 'Copacabana Palace Hotel',
    address: 'Av. Atlântica, 1702',
    city: 'Rio de Janeiro',
    state: 'RJ',
    type: 'accommodation',
  },
  {
    id: 'l2',
    name: 'Christ the Redeemer',
    address: 'Parque Nacional da Tijuca',
    city: 'Rio de Janeiro',
    state: 'RJ',
    type: 'tourist-spot',
  },
  {
    id: 'l3',
    name: 'Parents House',
    city: 'São Paulo',
    state: 'SP',
    type: 'accommodation',
  },
  {
    id: 'galeao-airport',
    name: 'Galeão International Airport',
    city: 'Rio de Janeiro',
    type: 'venue',
  },
  {
    id: 'narita-airport',
    name: 'Narita International Airport',
    city: 'Tokyo',
    type: 'venue',
  },
  {
    id: 'shibuya-office',
    name: 'Shibuya Business Tower',
    city: 'Tokyo',
    type: 'workplace',
  },
  {
    id: 'copacabana-beach',
    name: 'Copacabana Beach',
    city: 'Rio de Janeiro',
    type: 'venue',
  },
  {
    id: 'sugarloaf',
    name: 'Sugarloaf Mountain',
    city: 'Rio de Janeiro',
    type: 'tourist-spot',
  },
  {
    id: 'santa-teresa',
    name: 'Santa Teresa',
    city: 'Rio de Janeiro',
    type: 'venue',
  },
]

// Sample trips from tripService.ts
export const sampleTrips: NewTrip[] = [
  {
    id: 'rio-2024',
    title: 'Rio de Janeiro Adventure',
    destination: 'Rio de Janeiro, Brazil',
    country: 'Brazil',
    startDate: new Date('2024-03-15'),
    endDate: new Date('2024-03-22'),
    type: 'leisure',
    status: 'upcoming',
    userId: 'user-demo-1',
    settings: JSON.stringify({
      timezone: 'America/Sao_Paulo',
      dateFormat: 'US',
      currency: 'BRL',
      notifications: {
        email: true,
        push: true,
        reminders: true,
      },
      privacy: 'private',
    }),
    coverImage: 'https://images.unsplash.com/photo-1544984503-42b2de65b9ee?w=400&h=240&fit=crop',
  },
  {
    id: 'tokyo-business',
    title: 'Tokyo Business Trip',
    destination: 'Tokyo, Japan',
    country: 'Japan',
    startDate: new Date('2024-02-10'),
    endDate: new Date('2024-02-15'),
    type: 'business',
    status: 'active',
    userId: 'user-demo-1',
    settings: JSON.stringify({
      timezone: 'Asia/Tokyo',
      dateFormat: 'ISO',
      currency: 'JPY',
      notifications: {
        email: true,
        push: true,
        reminders: true,
      },
      privacy: 'private',
    }),
    coverImage: 'https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=400&h=240&fit=crop',
  },
  {
    id: 'london-family',
    title: 'London Family Vacation',
    destination: 'London, UK',
    country: 'United Kingdom',
    startDate: new Date('2024-07-20'),
    endDate: new Date('2024-07-30'),
    type: 'family',
    status: 'planning',
    userId: 'user-demo-1',
    settings: JSON.stringify({
      timezone: 'Europe/London',
      dateFormat: 'EU',
      currency: 'GBP',
      notifications: {
        email: true,
        push: true,
        reminders: true,
      },
      privacy: 'private',
    }),
    coverImage: 'https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?w=400&h=240&fit=crop',
  },
  {
    id: 'paris-honeymoon',
    title: 'Paris Honeymoon',
    destination: 'Paris, France',
    country: 'France',
    startDate: new Date('2023-10-05'),
    endDate: new Date('2023-10-15'),
    type: 'honeymoon',
    status: 'completed',
    userId: 'user-demo-1',
    settings: JSON.stringify({
      timezone: 'Europe/Paris',
      dateFormat: 'EU',
      currency: 'EUR',
      notifications: {
        email: true,
        push: false,
        reminders: false,
      },
      privacy: 'private',
    }),
    coverImage: 'https://images.unsplash.com/photo-1502602898536-47ad22581b52?w=400&h=240&fit=crop',
  },
  {
    id: 'iceland-adventure',
    title: 'Iceland Northern Lights',
    destination: 'Reykjavik, Iceland',
    country: 'Iceland',
    startDate: new Date('2024-12-01'),
    endDate: new Date('2024-12-08'),
    type: 'adventure',
    status: 'planning',
    userId: 'user-demo-1',
    settings: JSON.stringify({
      timezone: 'Atlantic/Reykjavik',
      dateFormat: 'ISO',
      currency: 'ISK',
      notifications: {
        email: true,
        push: true,
        reminders: true,
      },
      privacy: 'private',
    }),
    coverImage: 'https://images.unsplash.com/photo-1539066319756-03b4bbb67163?w=400&h=240&fit=crop',
  },
  {
    id: 'nyc-cultural',
    title: 'NYC Cultural Weekend',
    destination: 'New York, USA',
    country: 'United States',
    startDate: new Date('2024-05-03'),
    endDate: new Date('2024-05-06'),
    type: 'leisure', // Changed from 'cultural' to match enum
    status: 'upcoming', // Changed from 'confirmed' to match enum
    userId: 'user-demo-1',
    settings: JSON.stringify({
      timezone: 'America/New_York',
      dateFormat: 'US',
      currency: 'USD',
      notifications: {
        email: true,
        push: true,
        reminders: true,
      },
      privacy: 'private',
    }),
    coverImage: 'https://images.unsplash.com/photo-1496442226666-8d4d0e62e6e9?w=400&h=240&fit=crop',
  },
]

// Sample itinerary items from itineraryService.ts
export const sampleItineraryItems: NewItineraryItem[] = [
  // Rio de Janeiro Trip Items
  {
    id: 'rio-arrival',
    title: 'Flight Arrival - Rio de Janeiro',
    description: 'TAM Airlines JJ8070 - Land at Galeão International Airport',
    type: 'transport',
    startDate: new Date('2024-03-15T22:45:00'),
    endDate: new Date('2024-03-15T23:30:00'),
    isAllDay: false,
    locationId: 'galeao-airport',
    status: 'confirmed',
    priority: 'high',
    tags: JSON.stringify(['travel', 'arrival']),
    tripId: 'rio-2024',
    userId: 'user-demo-1',
    typeData: JSON.stringify({
      transportationType: 'flight',
      flightNumber: 'JJ8070',
      airline: 'TAM Airlines',
    }),
  },
  {
    id: 'rio-hotel-checkin',
    title: 'Hotel Check-in - Copacabana Palace',
    description: 'Check into Ocean View Suite',
    type: 'accommodation',
    startDate: new Date('2024-03-16T15:00:00'),
    endDate: new Date('2024-03-22T12:00:00'),
    isAllDay: false,
    locationId: 'l1',
    status: 'confirmed',
    priority: 'high',
    tags: JSON.stringify(['accommodation']),
    tripId: 'rio-2024',
    userId: 'user-demo-1',
    typeData: JSON.stringify({
      accommodationType: 'hotel',
      roomType: 'Ocean View Suite',
    }),
  },
  {
    id: 'christ-redeemer-visit',
    title: 'Christ the Redeemer Tour',
    description: 'Small group tour with professional guide',
    type: 'activity',
    startDate: new Date('2024-03-17T09:00:00'),
    endDate: new Date('2024-03-17T14:00:00'),
    isAllDay: false,
    locationId: 'l2',
    status: 'confirmed',
    priority: 'high',
    tags: JSON.stringify(['sightseeing', 'tour']),
    tripId: 'rio-2024',
    userId: 'user-demo-1',
    typeData: JSON.stringify({
      activityType: 'sightseeing',
      cost: { amount: 85, currency: 'USD' },
    }),
  },
  {
    id: 'copacabana-beach',
    title: 'Copacabana Beach Day',
    description: 'Relax on the famous beach, try local food',
    type: 'activity',
    startDate: new Date('2024-03-18T10:00:00'),
    endDate: new Date('2024-03-18T17:00:00'),
    isAllDay: false,
    locationId: 'copacabana-beach',
    status: 'planned',
    priority: 'medium',
    tags: JSON.stringify(['beach', 'leisure']),
    tripId: 'rio-2024',
    userId: 'user-demo-1',
    typeData: JSON.stringify({
      activityType: 'leisure',
    }),
  },
  {
    id: 'sugarloaf-mountain',
    title: 'Sugarloaf Mountain Cable Car',
    description: 'Panoramic views of Rio at sunset',
    type: 'activity',
    startDate: new Date('2024-03-19T16:00:00'),
    endDate: new Date('2024-03-19T19:00:00'),
    isAllDay: false,
    locationId: 'sugarloaf',
    status: 'confirmed',
    priority: 'high',
    tags: JSON.stringify(['sightseeing', 'sunset']),
    tripId: 'rio-2024',
    userId: 'user-demo-1',
    typeData: JSON.stringify({
      activityType: 'sightseeing',
      cost: { amount: 75, currency: 'USD' },
    }),
  },
  {
    id: 'santa-teresa-walk',
    title: 'Santa Teresa Neighborhood Walk',
    description: 'Explore historic neighborhood with colonial architecture',
    type: 'activity',
    startDate: new Date('2024-03-20T14:00:00'),
    endDate: new Date('2024-03-20T17:00:00'),
    isAllDay: false,
    locationId: 'santa-teresa',
    status: 'planned',
    priority: 'medium',
    tags: JSON.stringify(['culture', 'walking', 'historic']),
    tripId: 'rio-2024',
    userId: 'user-demo-1',
    typeData: JSON.stringify({
      activityType: 'cultural',
    }),
  },
  {
    id: 'rio-departure',
    title: 'Departure Flight',
    description: 'Return flight to home',
    type: 'transport',
    startDate: new Date('2024-03-22T15:30:00'),
    endDate: new Date('2024-03-22T16:30:00'),
    isAllDay: false,
    locationId: 'galeao-airport',
    status: 'confirmed',
    priority: 'high',
    tags: JSON.stringify(['travel', 'departure']),
    tripId: 'rio-2024',
    userId: 'user-demo-1',
    typeData: JSON.stringify({
      transportationType: 'flight',
    }),
  },

  // Tokyo trip items
  {
    id: 'tokyo-arrival',
    title: 'Arrive in Tokyo',
    description: 'Business trip arrival at Narita Airport',
    type: 'transport',
    startDate: new Date('2024-02-10T18:30:00'),
    endDate: new Date('2024-02-10T19:30:00'),
    isAllDay: false,
    locationId: 'narita-airport',
    status: 'confirmed',
    priority: 'high',
    tags: JSON.stringify(['business', 'travel']),
    tripId: 'tokyo-business',
    userId: 'user-demo-1',
    typeData: JSON.stringify({
      transportationType: 'flight',
    }),
  },
  {
    id: 'tokyo-meeting',
    title: 'Business Meeting - Shibuya Office',
    description: 'Quarterly review meeting with Japan team',
    type: 'work',
    startDate: new Date('2024-02-12T10:00:00'),
    endDate: new Date('2024-02-12T16:00:00'),
    isAllDay: false,
    locationId: 'shibuya-office',
    status: 'confirmed',
    priority: 'high',
    tags: JSON.stringify(['business', 'meeting']),
    tripId: 'tokyo-business',
    userId: 'user-demo-1',
    typeData: JSON.stringify({
      workType: 'meeting',
      company: 'Japan Office',
    }),
  },

  // London trip items
  {
    id: 'london-planning',
    title: 'Plan London Itinerary',
    description: 'Research attractions and book tickets',
    type: 'activity',
    startDate: new Date('2024-06-15T10:00:00'),
    endDate: new Date('2024-06-15T12:00:00'),
    isAllDay: false,
    status: 'planned',
    priority: 'medium',
    tags: JSON.stringify(['planning', 'research']),
    tripId: 'london-family',
    userId: 'user-demo-1',
    typeData: JSON.stringify({
      activityType: 'planning',
    }),
  },
]
